apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: divergente-component
  description: divergente app forked from Backstage
  tags:
    - v1alpha1
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=backstage'
spec:
  type: service
  lifecycle: production
  owner: devsecops
  system: divergentesystem
